name: cftr-esm2

channels:
  - conda-forge
  - pytorch

dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scipy
  - statsmodels
  - matplotlib
  - seaborn
  - pytorch
  - pip:
      - transformers
